version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ems_postgres_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ems_db
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ems_network_dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: ems_backend_dev
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ems_db?schema=public
      JWT_SECRET: dev-jwt-secret-key
      JWT_EXPIRATION: 24h
      ADMIN_LOGIN: admin
      ADMIN_PASSWORD: admin123
      ADMIN_DISPLAY_NAME: Administrator
      PORT: 3000
      FRONTEND_URL: http://localhost:3001
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - ems_network_dev
    command: sh -c "npm run prisma:migrate:dev && npm run prisma:seed && npm run start:dev"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: ems_frontend_dev
    environment:
      NODE_ENV: development
      NUXT_PUBLIC_API_BASE_URL: http://localhost:3000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.nuxt
    ports:
      - "3001:3000"
    depends_on:
      - backend
    networks:
      - ems_network_dev

networks:
  ems_network_dev:
    driver: bridge

volumes:
  postgres_data_dev: