version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: ems-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ems_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - ems-network

  # Backend API (Nest.js)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: ems-backend-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:password@db:5432/ems_db?schema=public
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
      - JWT_SECRET=dev-jwt-secret-key
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - ems-network
    command: npm run start:dev

  # Frontend (Nuxt.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: ems-frontend-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - ems-network
    command: npm run dev

volumes:
  postgres_data_dev:
    driver: local

networks:
  ems-network:
    driver: bridge